### ISSUE TITLE
How to build application using support-logging-client in debug and release mode

### ISSUE THREAD

**Issue by jay11ca39** [edgexfoundry/support-logging-client#13]
I am using support-logging-client SDK, in my application.

Following are the steps I followed:
1. Created a sample maven application. 

2. Included support-logging-client dependency in sample's pom.xml:

3. Included following in my sample application:
```
private final static EdgeXLogger logger = EdgeXLoggerFactory.getEdgeXLogger(App.class);
public static void main( String[] args ) {
logger.debug("Testing is successful");
}
```

4. I want to build my sample jar in:
   (i) **release mode [disable EdgeXLogger]** 
   (ii) **debug mode [enable EdgeXLogger]**

Do we have to set system property for **org.slf4j.Logger**?
Is any body tried this?
    
**System information:**
Ubuntu 14.04 [64-bit]
Eclipse Oxygen
Command used for building: mvn install

**Comment by jay11ca39** [comment]
@jpwhitemn 
Do you have any pointer for this issue?

**Comment by jay11ca39** [comment]
Hello All,
Is anybody is having info about this?

**Comment by jpwhitemn** [comment]
Hi Jay11ca39 - have you looked at the info on the Wiki about this service and the client library needs?  See https://wiki.edgexfoundry.org/display/FA/Architecture--Supporting+Services--Logging#Architecture--SupportingServices--Logging-LoggingServiceClientLibraryforJava and see if this helps

**Comment by jay11ca39** [comment]
Hi @jpwhitemn ,

I have went through the documentation of support-logging-client microservice. Which is a wrapper over **slf4jLogger** 

One simple solution to my problem: I can update the log4j properties using system properties based on application.properties file: 

For example: 
**application.properties** file can have : 
logging.level.mysdk=DEBUG

And on the basis of this info, I can set the system properties: 
**System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "debug");**

But as per my opinion, support-logging-client should provide apis to do this, app should not set the system properties directly.

**Comment by eb-oss** [comment]
I'm closing this ticket, as this repo is being archived.
